### ISSUE TITLE
image support

### ISSUE THREAD

**Issue by gianarb** [mobily/markdown-live#13]
hello!
Sorry but this project supports images?

``` bash
├── 004-jaws-work-with-lambda.md
└── img
    ├── cloudformation-stack.png
    ├── deploy.png
    ├── first_test_apigateway.png
    ├── foldering.png
    ├── jaws-startup.png
    └── new_module.png
```

This is my foldering, I run this command into the root
 mdlive --dir .

but this image (into the `004-jaws-work-with-lambda.md` file) return 404

``` md
![Start up JAWS](img/jaws-startup.png)
```

This is only a my problem? Thanks

**Comment by dfsq** [comment]
Hey @gianarb, so what was the problem? I can't figure it out too, should be something simple.

**Comment by gianarb** [comment]
Sorry, I don't remember :D

**Comment by dfsq** [comment]
Ha, no worries :)

**Comment by carlmartus** [comment]
So is there image support? I can't get it working. I'm using version 1.0.8.
