### ISSUE TITLE
Deep monitoring

### ISSUE THREAD

**Issue by gagle** [mobily/markdown-live#5]
Make `--dir` to monitor all the markdown files inside the tree structure, not only the first level.

**Comment by codelahoma** [comment]
If anyone does this, please make it a separate option, such as `[-r , --recurse]`.

There are _a lot_ of markdown files in the tree of a typical node application.

For instance, `find . -name '*.md'` in the root of [gulp-starter](https://github.com/greypants/gulp-starter) finds _1745_ files!.

**Comment by djKianoosh** [comment]
fyi.. i added a 'depth' option to recurse subdirs if you're interested... here's my fork:
https://github.com/djKianoosh/markdown-live
